/**
 * Vercel Serverless Function — Create Invitation
 * Endpoint: POST /api/invitations/create
 *
 * Body: { email: string, role: 'doctor' | 'receptionist' | 'assistant' }
 * Auth: Authorization: Bearer <supabase access_token>  (caller must be owner)
 *
 * Flow:
 *   1. Verify Supabase JWT.
 *   2. Resolve caller's profile via service role; require role === 'owner'
 *      with a non-null org_id.
 *   3. Refuse if the org is in 'test' status (test orgs are 1-user only).
 *   4. Validate email format and role against the invitable allow-list.
 *      Owners cannot invite other owners.
 *   5. Insert the invitation row (token / expires_at default-generated
 *      by Postgres). Audit-log via the audit_log insert.
 *   6. Return the new row's { id, token, expires_at, role, email, org_id,
 *      status }.
 */

import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL
const anonKey = process.env.VITE_SUPABASE_ANON_KEY
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY

const INVITABLE_ROLES = new Set(['doctor', 'receptionist', 'assistant'])
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Access-Control-Allow-Headers', 'Authorization, Content-Type')
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS')

  if (req.method === 'OPTIONS') return res.status(200).end()
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  if (!supabaseUrl || !anonKey || !serviceKey) {
    return res.status(500).json({ error: 'Server not configured' })
  }

  // 1. Verify JWT
  const authHeader = req.headers.authorization || ''
  if (!authHeader.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Missing auth token' })
  }
  const token = authHeader.slice('Bearer '.length).trim()
  if (!token) return res.status(401).json({ error: 'Missing auth token' })

  const userClient = createClient(supabaseUrl, anonKey)
  const { data: userData, error: userErr } = await userClient.auth.getUser(token)
  if (userErr || !userData?.user) {
    return res.status(401).json({ error: 'Invalid auth token' })
  }
  const userId = userData.user.id

  // 2. Resolve caller's profile
  const admin = createClient(supabaseUrl, serviceKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  })

  const { data: profile, error: profileErr } = await admin
    .from('profiles')
    .select('org_id, role')
    .eq('id', userId)
    .maybeSingle()
  if (profileErr) {
    console.error('[invitations/create] profile lookup failed:', profileErr)
    return res.status(500).json({ error: 'Internal error' })
  }
  if (!profile?.org_id) return res.status(403).json({ error: 'No org membership' })
  if (profile.role !== 'owner') {
    return res.status(403).json({ error: 'Only clinic owners can invite team members' })
  }

  // 3. Refuse test orgs
  const { data: org, error: orgErr } = await admin
    .from('orgs')
    .select('status')
    .eq('id', profile.org_id)
    .single()
  if (orgErr || !org) return res.status(404).json({ error: 'Org not found' })
  if (org.status === 'test') {
    return res.status(403).json({
      error: 'Test accounts cannot invite team members. Contact the operator for a real clinic account.',
    })
  }

  // 4. Validate body
  let body
  try {
    body = req.body && typeof req.body === 'object'
      ? req.body
      : JSON.parse(req.body || '{}')
  } catch {
    return res.status(400).json({ error: 'Invalid JSON body' })
  }

  const email = typeof body?.email === 'string' ? body.email.toLowerCase().trim() : ''
  const role = typeof body?.role === 'string' ? body.role.trim() : ''

  if (!email || !EMAIL_RE.test(email) || email.length > 255) {
    return res.status(400).json({ error: 'A valid email is required' })
  }
  if (!INVITABLE_ROLES.has(role)) {
    return res.status(400).json({
      error: `Invalid role. Must be one of: ${[...INVITABLE_ROLES].join(', ')}`,
    })
  }

  // 5. Insert the invitation. Token + expires_at default-generated by Postgres.
  const { data: inserted, error: insertErr } = await admin
    .from('invitations')
    .insert({
      org_id: profile.org_id,
      email,
      role,
      invited_by: userId,
      status: 'pending',
    })
    .select('id, org_id, email, role, token, status, invited_at, expires_at')
    .single()
  if (insertErr) {
    console.error('[invitations/create] insert failed:', insertErr)
    return res.status(500).json({ error: 'Failed to create invitation' })
  }

  // Audit log
  const { error: auditErr } = await admin.from('audit_log').insert({
    org_id: profile.org_id,
    acting_user_id: userId,
    effective_user_id: null,
    action: 'invitation.create',
    entity_type: 'invitation',
    entity_id: inserted.id,
    payload: { email, role },
  })
  if (auditErr) {
    console.error('[invitations/create] audit log failed:', auditErr)
    // Non-fatal — the invitation is real.
  }

  return res.status(200).json(inserted)
}
